### ISSUE TITLE
Move out of HaikuArchives

### ISSUE THREAD

**Issue by pulkomandy** [pulkomandy/Renga#86]
It seems I have pretty much taken ownership of this project. The old Jabber4Haiku is no more, and Renga replaces it. I hope that's fine and no one will miss it.

@HaikuArchives/admins, do you agree with moving this to my own github? I'd rather do this before I add it to the xmpp.org website, so I can use the new URL there. I discussed this with other XMPP people and they were confused by the "HaikuArchives" name and the description of the organization.

**Comment by waddlesplash** [comment]
Yes, fine by me.

**Comment by kallisti5** [comment]
Lets point this to @pulkomandy 's and set it as archived / read-only.   That will preserve and existing automation around it (aka haikuports)

**Comment by waddlesplash** [comment]
GitHub automatically instates redirects when repositories are removed. In order to preserve the issue tracker we need to move the repo.

**Comment by korli** [comment]
Fine by me with moving and updating the recipe.

**Comment by pulkomandy** [comment]
I have now released a new version on haikuports pointing to the new place.
